id: PFBFA78E3
initial_creation_type: input
source_metadata:
  Title: Bhavasaṅkrānti Śāstra
  Editor: Shastri, Aiswami
  Publisher: The Adyar Library
  Place of Publication: Madras
  Year: '1938'
  Bhavasaṅkrāntiṭīkā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:53:39.567020'
last_modified_at: '2022-03-08T16:53:39.567028'
